# Versão do Docker Compose
version: "3.8"

# Definição dos serviços (contêineres)
services:
  # Serviço da API em Python
  python_api:
    build: ./analise_lances
    container_name: python_api_service
    restart: always
    env_file:
      - ./analise_lances/.env
    ports:
      - "8000:8000"
    networks:
      - app_network
    # O volume abaixo é útil para desenvolvimento (reflete mudanças no código sem rebuild)
    volumes:
      - ./analise_lances:/code

  # Serviço do Backend em Node.js
  nodejs_backend:
    build: ./capitao_consorcios_backend
    container_name: nodejs_gateway_service
    restart: always
    env_file:
      - ./capitao_consorcios_backend/.env
    ports:
      - "3000:3000"
    depends_on:
      python_api:
        # Espera o serviço Python iniciar
        condition: service_started
    networks:
      - app_network
    # O volume abaixo é útil para desenvolvimento
    volumes:
      - ./capitao_consorcios_backend:/usr/src/app

# Define a rede compartilhada para que os serviços possam se comunicar pelo nome
networks:
  app_network:
    driver: bridge
